package GUI;

import java.awt.Desktop;
import java.awt.Dimension;

import javax.swing.*;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.awt.Font;
import java.awt.Component;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.FlowLayout;

import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;



/**
 * For now this is the sole class containing code for the 
 * Quoridor GUI.
 * <br><br>
 * Note*:  A large part of this code was generated by the 
 * WindowBuilder plugin for Eclipse
 * 
 * @author Nick
 *
 */
public class FirstWindow extends JFrame{
	public final static String MAIN_WINDOW_TITLE = "FirstWindow";
	public final static String MENU_BAR_NAME = "MenuBar";
	public final static String LABEL = "Hello";
	
	public final static String BUTTON_TEXT = "New Game";
	public final static String LABEL_NAME = "lblWelcome";

	// messages displayed by the label
	public static final String INITIAL_MESSAGE = "Welcome To Quoridor!";
	
	public final static String NEW_GAME_MESSAGE = "This will eventually start a new game!";

	private boolean visible;
	private boolean playAI;
	private boolean fourPlayerGame=true;
	
	public FirstWindow() {
		
		super();
		visible = true;
		setName(MAIN_WINDOW_TITLE);
		setTitle(MAIN_WINDOW_TITLE);
		setSize(640, 480);
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		
		// Adding a menu bar that appears at the top of the window
		JMenuBar menuBar = new JMenuBar();
		menuBar.setName(MENU_BAR_NAME);
		setJMenuBar(menuBar);
		
		// Adding an menu called "File" to the menu bar
		JMenu mnFile = new JMenu("File");
		menuBar.add(mnFile);
		
		// Adding a 'New Game' menu item to the 'File' menu
		JMenuItem mntmNewGame = new JMenuItem("New Game");
		mntmNewGame.addMouseListener(new MouseAdapter() {
			// Add actions to be preformed when the item is clicked here
			@Override
			public void mousePressed(MouseEvent e) {
				// Close the welcome menu and bring up the game board
				dispose();
				BoardGUI gameBoard = new BoardGUI(playAI, fourPlayerGame);	
			}
		});
		mntmNewGame.setHorizontalAlignment(SwingConstants.LEFT);
		mnFile.add(mntmNewGame);
		
		
		// Adding a  'Save' menu item to the 'File' menu
		JMenuItem mntmSave = new JMenuItem("Save");
		mnFile.add(mntmSave);
		
		// Adding a 'Help' menu to the menu bar
		JMenu mnHelp = new JMenu("Help");
		menuBar.add(mnHelp);
		
		// Adding a 'QuoridorWiki' menu item to the 'Help' menu
		JMenuItem mntmQuoridorWiki = new JMenuItem("Quoridor Wiki");
		mntmQuoridorWiki.setName("Quoridor Wiki");
		mntmQuoridorWiki.addMouseListener(new MouseAdapter() {
			// the on mouse press event
			@Override
			public void mousePressed(MouseEvent e) {
				URI url = null;
				try {
					url = new URI("http://en.wikipedia.org/wiki/Quoridor");
				} catch (URISyntaxException ex) {
					// TODO Auto-generated catch block
					ex.printStackTrace();
				}
				try {
					// try to open the default browser using the given url
					Desktop.getDesktop().browse(url);
				} catch (IOException ex) {
					// TODO Auto-generated catch block
					ex.printStackTrace();
				}
			}
		});
		mnHelp.add(mntmQuoridorWiki);
		
		// Adding a button to the frame
		JButton btnNewGame = new JButton("New Game"); // sets the text
		btnNewGame.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				// Close the welcome menu and bring up the game board
				dispose();
				BoardGUI gameBoard = new BoardGUI(playAI, fourPlayerGame);	
			}
		});
		btnNewGame.setName("btnNewGame");
		
		// Adding a welcome label to the frame
		JLabel lblWelcomeToQuoridor = new JLabel(INITIAL_MESSAGE);
		lblWelcomeToQuoridor.setFont(new Font("Tahoma", Font.BOLD, 18));
		lblWelcomeToQuoridor.setName(LABEL_NAME);
		
		// Checkbox for selecting to play the AI
		JCheckBox chckbxAI = new JCheckBox("Play AI");
		chckbxAI.addItemListener(new ItemListener() {
			public void itemStateChanged(ItemEvent arg0) {
				playAI = !playAI;
			}
		});
		
		JRadioButton rdbtn4Players = new JRadioButton("4 Players");
		rdbtn4Players.setSelected(true);
		rdbtn4Players.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				fourPlayerGame = true;
			}
		});
		
		JRadioButton rdbtn2Players = new JRadioButton("2 Players");
		rdbtn2Players.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				fourPlayerGame = false;
			}
		});
		
		//Group the radio buttons.
	    ButtonGroup group = new ButtonGroup();
	    group.add(rdbtn2Players);
	    group.add(rdbtn4Players);
		
		// set the layout of the frame to be a GroupLayout and arrange the components
		GroupLayout groupLayout = new GroupLayout(getContentPane());
		groupLayout.setHorizontalGroup(
			groupLayout.createParallelGroup(Alignment.TRAILING)
				.addGroup(groupLayout.createSequentialGroup()
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addGroup(groupLayout.createSequentialGroup()
							.addGap(214)
							.addComponent(lblWelcomeToQuoridor))
						.addGroup(groupLayout.createSequentialGroup()
							.addGap(268)
							.addComponent(chckbxAI, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(200, Short.MAX_VALUE))
				.addGroup(groupLayout.createSequentialGroup()
					.addContainerGap(242, Short.MAX_VALUE)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(btnNewGame, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE)
						.addGroup(groupLayout.createSequentialGroup()
							.addComponent(rdbtn4Players)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(rdbtn2Players)))
					.addGap(216))
		);
		groupLayout.setVerticalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblWelcomeToQuoridor)
					.addGap(18)
					.addComponent(btnNewGame, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
					.addGap(16)
					.addComponent(chckbxAI)
					.addGap(23)
					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
						.addComponent(rdbtn2Players)
						.addComponent(rdbtn4Players))
					.addContainerGap(242, Short.MAX_VALUE))
		);
		getContentPane().setLayout(groupLayout);
	
		// make everything visible
		setVisible(visible);
	}
}
